### ISSUE TITLE
demo运行不了

### ISSUE THREAD

**Issue by ymsying** [GeLeis/App_NoirDemo#1]
demo下载后设置monochromatic为1，点击”点击进入TableView“崩溃，报[__NSCFDictionary CGColor]: unrecognized selector sent to instance 0x600002c91940 ，未找到崩溃原因

**Comment by GeLeis** [comment]
UIColor+Common.m文件45行代码注掉吧，这里强制返回了父类UIColor，系统可能会对子类UIDynamicSystemColor有 其他的处理，之前写这个代码的时候在模拟器、真机上没有问题，UIDynamicSystemColor这个HOOK处理在我升级XCODE11.6后也是崩溃，如果想处理系统的默认颜色，比如蓝色，可以HOOK系统方法[UIColor systemBlueColor]等

**Comment by ymsying** [comment]
对的，UIDynamicSystemColor这个类不能hook
